### ISSUE TITLE
Social Club-Only Integration (Basic macOS Version)

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [tylerbrawl/Galaxy-Plugin-Rockstar#10]
Hi,

Although there is no RockstarLauncher for macOS, it is still beneficial for some people to just list their games from different platforms (like PSN or XBOX) even if they cannot be installed.

As owned games (#2) should work without client, it would be nice to have it shipped after basic functionality is done. I can help with testing.

**Comment by tylerbrawl** [comment]
I will certainly look into that after the re-authentication issue is fixed. I do not own a Mac computer, so I would certainly need the help of others for testing. Owned games works without a client, but it only shows the user's played games. Still, the list is accurate enough, and in fact, it might be better suited for a Social Club-only integration than the user's launcher games. 

Besides that, friend imports should work fine. I have also figured out how to get the user's unlocked achievements from the Social Club API, but I have not been able to test it myself. (The list generated for GTA V seems to be replaced by the list generated by the Steam plugin in my situation.) I would also appreciate if you or somebody else could test the achievements functionality by downloading the source files found in the [achievements-WIP branch](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/tree/achievements-WIP) of the plugin and using the dependencies from the latest release.

**Comment by tylerbrawl** [comment]
The newest release includes basic support for macOS, but I am unable to test it. If you or anybody else finds any errors, then please let me know.

**Comment by FriendsOfGalaxy** [comment]
Hi, I've created PR for this, as it is difficult for you to work without mac #13

**Comment by tylerbrawl** [comment]
The Mac integration support that you added has been implemented in the release of v0.2.1.
