### ISSUE TITLE
gta4 being recognised as gta5?

### ISSUE THREAD

**Issue by derailedition** [tylerbrawl/Galaxy-Plugin-Rockstar#100]
I think I'm seeing this right, the recently released gta4 is also being recognised as gta5 in the plugin?

**Comment by tylerbrawl** [comment]
I have to update the plugin on a per-game basis, so it makes sense that it doesn't work. I will push a new update to the repository for this.

**Comment by tylerbrawl** [comment]
When the plugin is updated, GTA IV should appear in your library as separate from GTA V. It should happen automatically within the next few days. If you want to test it early, then you may use the attached build to do so. Instructions for manual plugin installation can be found on the repository home page.

[Plugin.zip](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/4396195/Plugin.zip)

**Comment by derailedition** [comment]
ahh alright. cool. I'll have a look

**Comment by derailedition** [comment]
btw. I'll add it on here instead of creating a new one. san andreas is also not picked up by the integration yet or is it supposed to be?

**Comment by derailedition** [comment]
ok. all games working for me with the latest update there.
