### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by derailedition** [tylerbrawl/Galaxy-Plugin-Rockstar#104]
integration just says 'offline' for the last couple days here. clicking retry doesnt do anything. disconnecting/deleting/redownloading/connecting again doesnt seem to do anything either. double checked the rockstar launcher itself, and everything seems normal there.

**Comment by tylerbrawl** [comment]
Sorry about that. Thanks for reporting the issue to me. It appears as though Rockstar has altered their authentication flow slightly (mainly, they just moved the generation of a specific cookie elsewhere). I will push an update to the repository now. If you want the update now, then download and install the attached build.

[Rockstar.zip](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/4452518/Rockstar.zip)
