### ISSUE TITLE
Extension callled Riot?

### ISSUE THREAD

**Issue by DerRockWolf** [tylerbrawl/Galaxy-Plugin-Rockstar#11]
The extension is called Riot in my menus. Is that wanted? 
![image](https://user-images.githubusercontent.com/50499906/67165473-a66ef400-f385-11e9-9f42-2f76f9c71155.png)
![image](https://user-images.githubusercontent.com/50499906/67165482-bdade180-f385-11e9-9251-2371aa07751c.png)

**Comment by DarkNeooo** [comment]
Yeah, because until today there were no platform id for Rockstar Games Launcher in API.

**Comment by DerRockWolf** [comment]
Oh okay. Thanks for the reply.

**Comment by tylerbrawl** [comment]
Since the platform ID has been added, I will change the platform ID to Rockstar by the next update. I have just been working hard to fix re-authentication. The next update should be out fairly soon, unless any major issues are reported.

**Comment by tylerbrawl** [comment]
This has been fixed with the final release of v0.2. The platform ID is now listed correctly as Rockstar.
