### ISSUE TITLE
Rockstar (offline)

### ISSUE THREAD

**Issue by hightower5** [tylerbrawl/Galaxy-Plugin-Rockstar#114]
This plugin doesn't work any more. GOG says: Rockstar Offline (repeat)

**Comment by shovik-g** [comment]
When I try to connect, it opens a page with RDR2 update details, which does not auto close. Closing it manually, sets the integration back to disconnected. Should I raise this in another issue?

**Comment by FaithTheSlayer** [comment]
Was working fine even after yesterdays update to RDO but then around bedtime it stopped working.

**Comment by BradB111** [comment]
I would also like to add to the list of those affected:
![image](https://user-images.githubusercontent.com/17122433/88840499-7c7c1500-d1d4-11ea-8aea-9a96bf38e266.png)

**Comment by FernanDell** [comment]
I also have the same issue.

**Comment by b1oki** [comment]
![image](https://user-images.githubusercontent.com/1561897/89099242-45da1080-d407-11ea-8ff9-f1bed819bc65.png)

same issue

**Comment by suratovvlad** [comment]
Same thing

**Comment by TheMulti0** [comment]
Same

**Comment by ElAlderson** [comment]
Same issue here.

**Comment by MrJabberwock** [comment]
Same as well.

**Comment by zunzun1** [comment]
Same here

**Comment by basilrey** [comment]
Same Issue Here

**Comment by tylerbrawl** [comment]
Sorry about the long wait; I've been away from this plugin for quite some time in pursuit of other topics. Looking at network traffic from Rockstar's website, it appears as if they made rather drastic changes to their API recently. It might take some time before I can get the plugin working again.

**Comment by tylerbrawl** [comment]
I just pushed a new update to the ``fog_release`` branch that seems to fix this issue. The new update should be automatically downloaded through Galaxy 2.0 soon. In the meantime, I will leave the issue open in case any additional problems occur with the new version.

(For those wondering why the plugin broke, Rockstar, for some reason, decided to refactor a lot of their authentication system for their main domain (rockstargames.com); this resulted in the plugin attempting to access an endpoint that no longer exists.)

**Comment by TheMulti0** [comment]
> I just pushed a new update to the `fog_release` branch that seems to fix this issue. The new update should be automatically downloaded through Galaxy 2.0 soon. In the meantime, I will leave the issue open in case any additional problems occur with the new version.
> 
> (For those wondering why the plugin broke, Rockstar, for some reason, decided to refactor a lot of their authentication system for their main domain (rockstargames.com); this resulted in the plugin attempting to access an endpoint that no longer exists.)

Excellent, I can see you have been working hard on this big change.
I will check this new change today and let you know.
Thanks for helping out!

**Comment by hightower5** [comment]
Where I can found a directdownload of the new release?

**Comment by FaithTheSlayer** [comment]
Still not working

**Comment by TheMulti0** [comment]
Not working for me too

**Comment by BradB111** [comment]
As far as I can tell the new version has not been pushed to the client quite yet. 0.5.4 is what is shown in the plugin manifest that has just been downloaded and this is the same version number for the plugin I manually deleted in appdata that had the 'file edited on' dates of 29/6/20 (when I installed GOGGalaxy)

So may still not be available via the client at the moment.

**Comment by ElAlderson** [comment]
True. That's why @tylerbrawl told it is in the `fog_release` and it would be pushed to the client soon.

**Comment by BradB111** [comment]
> True. That's why @tylerbrawl told it is in the `fog_release` and it would be pushed to the client soon.

Understood. Just wanting to explain to those who may find in still not working as to the reason that may be.

**Comment by FriendsOfGalaxy** [comment]
For those who want to test it before releasing in Galaxy there are builds:
https://github.com/FriendsOfGalaxy/galaxy-integration-rockstar/actions/runs/194027690

- Close Galaxy
- remove rockstar integration from `%localappdata%\GoG.com\Galaxy\plugins\installed`
- unpack downloaded zip to `%localappdata%\GoG.com\Galaxy\plugins\installed`  (renaming directory after that is not required)
- Launch Galaxy

**Comment by FaithTheSlayer** [comment]
> I'm testing. If everything is ok, should be merged soon, maybe tomorrow.
> 
> For those who want to test it before releasing in Galaxy there are builds:
> https://github.com/FriendsOfGalaxy/galaxy-integration-rockstar/actions/runs/194027690
> 
> * Close Galaxy
> * remove rockstar integration from `%localappdata%\GoG.com\Galaxy\plugins\installed`
> * unpack downloaded zip to `%localappdata%\GoG.com\Galaxy\plugins\installed`  (renaming directory after that is not required)
> * Launch Galaxy

THANK YOU!

**Comment by zunzun1** [comment]
Works fine thanks.

**Comment by TheMulti0** [comment]
This indeed works!

**Comment by tylerbrawl** [comment]
I'm glad that it seems to be working for everyone again. I will go ahead and close this issue.
