### ISSUE TITLE
Stopped working after Red Dead Online Update on 28th

### ISSUE THREAD

**Issue by FaithTheSlayer** [tylerbrawl/Galaxy-Plugin-Rockstar#115]
Please fix!

**Comment by Euxiniar** [comment]
I can confirm that I can't connect anymore

**Comment by felipeocr** [comment]
Same error here.

**Comment by ElAlderson** [comment]
This is the same issue as #114 . Having the same problem.

**Comment by FaithTheSlayer** [comment]
Isn't anyone going to fix it?

**Comment by ElAlderson** [comment]
I think people are trying their best for now. For us, the best we can do is raise a flag and then wait.

**Comment by tylerbrawl** [comment]
I'm closing this because it appears to be a duplicate of #114. Please discuss the issue further there.
