### ISSUE TITLE
Importing Achievements Fails

### ISSUE THREAD

**Issue by tylerbrawl** [tylerbrawl/Galaxy-Plugin-Rockstar#12]
For some reason, the list of achievements that the user has unlocked fails to appear on the Galaxy 2.0 client. However, the log file shows that the user's earned achievements are indeed being found from the Social Club API. 

Is it possible that Galaxy 2.0 disallows achievements for various platforms? I know that installing games is not possible on some (for instance, Newegg, which I used as my first temporary platform ID substitution, does not allow the user to install games).

**Comment by FriendsOfGalaxy** [comment]
Hey,

Galaxy first needs definitions of achievements (all achievements which are possible to unlock in the game) before they can be reported and shown for a given platform.

Please send us an email to friendsofgalaxy@gmail.com with a json file containing up-to-date achievements for Rockstar in a form similar to this.

```
{
        "release_per_platform_id": "{platform_id}_{game_id}",
        "name": "Achievement_name",
        "description": "Achievement_description.",
        "api_key": "achievement_api_key",
        "image_url_unlocked": "image_achievement_unlocked",
        "image_url_locked": "image_achievement_locked"
},
```

Other possibility is sending us an url or an endpoint which provides similar information.

Bear in mind not all of those are required and in worst case scenario api_key and name would suffice.

We will pass the provided information to GOG and hopefully get those achievements working as soon as possible.

Hope this helps!

**Comment by tylerbrawl** [comment]
Thanks for this information. I have sent an e-mail containing the required information.

**Comment by tylerbrawl** [comment]
Has there been any new information regarding achievements as of late?

**Comment by FriendsOfGalaxy** [comment]
Not yet, I will let you know as soon as i get any response from them.

**Comment by FriendsOfGalaxy** [comment]
Hey, I've got information that achievements should work now.

**Comment by tylerbrawl** [comment]
I just tested the achievements feature by changing the ``ARE_ACHIEVEMENTS_IMPLEMENTED`` boolean in ``consts.py``, and it does indeed seem to be working properly. I will update the plugin to account for this.
