### ISSUE TITLE
FOG Fork Autoupdate Request

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [tylerbrawl/Galaxy-Plugin-Rockstar#15]
Hey, 

we're planning on creating a fork/autoupdate system with selected plugins. This would allow us to create a list of curated and reviewed plugins which could be of use to GOG Galaxy people.

So your plugin is welcomed! You will be credited as the creator and developer of the plugin in [our fork readme](https://github.com/FriendsOfGalaxy/galaxy-integration-rockstar) and possibly other places.

Before we do that we need to ask you to create a `fog_release` branch which would contain only your plugin code, `manifest.json` and a `requirements.txt` file. The `requirements.txt` has to be in repository root and have only pinned dependencies (using `==` for example: `galaxy.plugin.api==0.55`). For Github releases, we will include the whole directory where `manifest.json` is placed (let it call SOURCE_DIR) and build dependencies directly there. So everything outside the SOURCE_DIR will be skipped!

The second option is to tweak your master branch if you are OK with changing your current structure. Code for repo synchronization can be found here: https://github.com/FriendsOfGalaxy/galaxy-integrations-updater

**Comment by tylerbrawl** [comment]
Here is the fog_release branch: https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/tree/fog_release

If you have any issues with it, then let me know.

**Comment by FriendsOfGalaxy** [comment]
Hey, there is error while building:
https://github.com/FriendsOfGalaxy/galaxy-integration-rockstar/commit/54eabf1dae2ecebdb7f9e6377f7b8bc6f65873eb/checks?check_suite_id=287775093
```
There are incompatible versions in the resolved dependencies:
  aiohttp==3.6.2 (from -r requirements.txt (line 2))
  aiohttp==3.5.4 (from galaxy.plugin.api==0.55->-r requirements.txt (line 1))
```

Please remove aiohttp from requirements.txt, as it is already requested by galaxy api.

---

BTW you can get rid of `requests` dependency by creating session using aiohttp.
This is now recommended way of working with requests, see api docs:
https://galaxy-integrations-python-api.readthedocs.io/en/latest/galaxy.http.html (HttpClient is deprecated)

**Comment by tylerbrawl** [comment]
The ```aiohttp``` dependency has been removed from requirements.txt. In addition, both the master branch and the fog_release branch no longer depend on the ```requests``` module.

Let me know if any additional errors occur.

**Comment by FriendsOfGalaxy** [comment]
Hi, thanks for fix! Build is passing. 

I see you made quite a few changes to drop requests... appreciate that. It is probably possible make the code simpler (maybe creating another session instead of manual cookie removal?) but let us focus on shipping the plugin first.

So build is passing. Review: I've put some comments on user sensitive data:
https://github.com/FriendsOfGalaxy/galaxy-integration-rockstar/pull/2#pullrequestreview-309779467
I've missed this in my last PR, I'm sorry for bouncing it again to you.

**Comment by tylerbrawl** [comment]
Don't worry about it; concealing sensitive data is important. I have updated the fog_release and master branches to hide sensitive data from the log by default.

In regards to cookie removal, I was not sure of any better way to remove cookies. I suppose a new session could be created after every removal, but that just seems inefficient. I wish that aiohttp.CookieJar included a means to remove a cookie from the cookie jar manually, but perhaps they have their reasons for not doing so.

**Comment by tylerbrawl** [comment]
I have a quick question for you. Should I push changes to the fog_release branch as soon as they are made, or only when the source code is in a production-ready state? I released a pre-release of the next version, but I am not sure if the changes should be pushed to this branch.

**Comment by FriendsOfGalaxy** [comment]
Only stable releases should be shipped (or "stable" in the meaning of 0.*/beta release). This also requires higher version than in previous master or current PR.

So I'm waiting for resolving sensitive data logs on fog_release; you don't have to add new features/bugfixes meantime if you feel they are not production ready.

**Comment by tylerbrawl** [comment]
Thanks for letting me know.

**Comment by FriendsOfGalaxy** [comment]
You may treat fog_release as typical release branch. Get inspiration from this: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
But small projects do not need sophisticated workflow, if I were you I would just use 3 layers: 
- release branch (fog_release)
- your master branch
- feature branches
Make releases from master at any point you wish, we will make releases from every new version on fog_release

Hope that helps :)

**Comment by tylerbrawl** [comment]
This is a very useful resource! As you have probably noticed, I still have to get used to dealing with Git branches, merge conflicts, etc., so your help is definitely appreciated.

On a separate note, I apologize for the lengthy delay in committing recent changes to the release branch. There have been many complications recently, with some caused by the migration to ```aiohttp``` and others newly found (for instance, RDR 2 was not launching [until a recent fix](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/commit/0ce7af80c577f4a39357a206b28866c113747386)). As suggested, sensitive data will be hidden by default with the next push to the release branch, along with a whole slew of additional changes, including basic game time tracking.

**Comment by FriendsOfGalaxy** [comment]
No problem, I'll wait for your changes. I understand that moving to asyncio was also a big change. It would be great to merge first stable version on `fog_release` so if it is not a problem, please prioritize blockers and bugfixes over new features.

Some additional tips:
- avoid pushing to master - use feature branches and merge them if ready. Then it is easier to deal with history for example to revert changes: `git revert #SHA` (just one commit!)
- keep separation for bugfixes and new features in different branches
- in case of code refactor test the project for regressions before release

If this helps to keep fog_release and master in sync, you can bring back those files:
![6fd9bce846d8c79cd5ae17afaa9e5e70](https://user-images.githubusercontent.com/48480506/68297599-af570980-0097-11ea-9901-06c98e8c50b2.png)

Those will be not used for building release for users on fog, as we only pack content of `src`

**Comment by tylerbrawl** [comment]
I have finally released v0.3 as a final release, and the fog_release branch has been updated accordingly. I also plan to begin using this new Git structure for future changes.

If there are any issues that you notice with the latest version, then please let me know. Otherwise, feel free to let @Mixaill know about your fork of this plugin for their ```awesome-gog-galaxy``` list.

**Comment by FriendsOfGalaxy** [comment]
Hi, thanks, it looks OK.
I've just realized we cannot use your repo until you add a LICENSE. Please add a one (preferably MIT).

**Comment by tylerbrawl** [comment]
I just added an MIT license to the project. Thanks for letting me know.

**Comment by tylerbrawl** [comment]
As a side note, what do you think about my custom game time implementation? If you think that it works well enough, I am considering releasing it as a standalone module for other people creating Galaxy 2.0 integrations. Many of the integrations listed on [awesome-gog-galaxy](https://github.com/Mixaill/awesome-gog-galaxy) do not have a method for importing game time, perhaps because the platform does not support game time tracking or, as in my situation, there is no known way to retrieve the game time.

**Comment by FriendsOfGalaxy** [comment]
Thanks, everything works as expected.

> As a side note, what do you think about my custom game time implementation?

It is a nice idea and great value for platforms w/o game time tracking. Do it ;)

However it has some issues:
1. game time are only local and can be lost (need cloud storage)
2. do not count game time when is idle (Galaxy has smart watching for mouse hooks for their games)
3. this is somehow against the how the "disconnect" works (actually it workarounds this) so users may not expect this.

In the end I really hope Galaxy will support game time tracking out of the box, so we could avoid doing workarounds. For example just give proper executable path and they can track game-time as do for GOG games. You can make a proposal for them as mantis issue and/or on API site. But for know, standalone project for time tracking is OK.

**Comment by tylerbrawl** [comment]
I'll see what I can do until GOG add it themselves. Thanks for the feedback!

**Comment by tylerbrawl** [comment]
@FriendsOfGalaxy - I finally got around to making that standalone project for time tracking. I made it a separate module called ```galaxyutils```, which you can check out from its repository at https://github.com/tylerbrawl/Galaxy-Utils. I also added a configuration file parser for plugin developers to create their own settings that users can then customize. Documentation for this module can be found at https://galaxy-utils.readthedocs.io/en/latest/.
