### ISSUE TITLE
Sign in to plugin does not work

### ISSUE THREAD

**Issue by Twiebie94** [tylerbrawl/Galaxy-Plugin-Rockstar#150]
When I sign in to rockstar games launcher / the rockstar plugin, all first windows work fine.

After confirming the password, the window will  reload and shows an empty windows.
It will stay there (I tried to leave it open for around an hour). 

Reinstalling the plugin or gog results in the same behavior.

Afterall the login will not be sucessful after closing the window.

![grafik](https://user-images.githubusercontent.com/14784949/158861542-8a108ee3-7b13-432a-9331-9fdc9c3fff72.png)

**Comment by tylerbrawl** [comment]
I actually recently fixed this issue with #149. The update might take some time to be pushed to the Galaxy 2.0 client, but the issue should fix itself momentarily.

I'll close this issue for now. If after some time (e.g., a few days) the plugin still does not connect, then we can re-open this issue.

**Comment by Twiebie94** [comment]
@tylerbrawl - the manifest.json shows 0.5.13 
As there are current releases in the repo, is there any way of updating the plugin?

**Comment by tylerbrawl** [comment]
The latest version is v0.5.14. I don't have control of when the plugin gets updated for Galaxy 2.0; I just push the changes to the `fog_release` branch when they are done.

If the release still has not been downloaded, then you can indeed patch the plugin yourself. I am attaching the latest version to this comment. You can install it manually by going to the plugin's installation directory and replacing the files inside with those contained within the attached .zip archive.

I'm not at my desktop computer, so I cannot give exact instructions as to where the plugin is installed. However, I do know that you can find it on Windows at `%LOCALAPPDATA%\GOG.com\Galaxy\plugins\installed\[Somewhere Here]` or on Mac at `~/Library/Application Support/GOG.com/Galaxy/plugins/installed/[Somewhere Here]`. Once you replace the files, you will need to fully restart Galaxy 2.0 for the changes to take effect.

Please let me know if you have any additional questions.

[Rockstar Plugin v0.5.14.zip](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/8319482/Rockstar.Plugin.v0.5.14.zip)
