### ISSUE TITLE
Plugin won't log in

### ISSUE THREAD

**Issue by Gittun** [tylerbrawl/Galaxy-Plugin-Rockstar#151]
After entering my credentials the window 'Login to Rockstar Games Social Club' gets stuck on a grey screen and won't close on its own. If I close it manually, it acts as if I am not connected yet.
![image](https://user-images.githubusercontent.com/36198374/159165534-dcab2ea3-c18c-461c-8a30-10848a77d602.png)
[plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/8311363/plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log)

**Comment by tylerbrawl** [comment]
As @DSPAUL mentions, manually updating the plugin should fix it. I posted about it [here](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/issues/150#issuecomment-1074466754). I'll close the issue for now.
