### ISSUE TITLE
Better owned games implementation Suggestion/Research 

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [tylerbrawl/Galaxy-Plugin-Rockstar#2]
Hey,

great work with plugin! I've been doing some research into rockstar myself and just like you stumbled into issues with getting owned games. 

I'd like to share some of my research and suggestions regarding retrieving them, feel free to do with it whatever you want. 

From what i understand currently a user which has the plugin but doesn't have rockstargames launcher installed won't see any of his owned games. I think that is the biggest issue but it could be mitigated/minimized by some requests magic. 

In www.rockstargames.com domain auth scope there is a https://www.rockstargames.com/auth/get-user.json call which returns games which user has played (and only some of them). This call uses cookie based auth.

![image](https://user-images.githubusercontent.com/48480506/66118893-c9ed1d00-e5d7-11e9-9322-ceab7dcbe313.png)

![image](https://user-images.githubusercontent.com/48480506/66118877-b9d53d80-e5d7-11e9-8789-2fc18d85b8b7.png)

In socialclub.rockstargames.com auth scope there is a 
https://scapi.rockstargames.com/profile/getprofile?nickname={nickname}&maxFriends=3
call which in its response returns 'gamesOwned' but it looks like the list only gets populated with the games you already played too.  The games list is slightly different than the one in get-user.json call too.

Auth to this endpoint is done by a Bearer token which is set as a cookie when doing a request to 
https://socialclub.rockstargames.com/Blocker/AuthCheck but im not sure what are the preqrequesites to the AuthCheck call itself.

**One idea was to combine the two list from those calls into one.**

Another idea is to use https://socialclub.rockstargames.com/ajax/getGoogleTagManagerSetupData?_={somenumbers} call. In its response it also gives a list of games which the user has already played but it appears to already combine the 2 endpoints above (meaning the list is complete). 

Auth to this endpoint is done by cookies inserted as a header and a RequestVerificationToken which is hiding in html when doing a get request on https://socialclub.rockstargames.com/ 
 <input name="__RequestVerificationToken" type="hidden" value="token" />

additionally this ajax endpoint needs {somenumbers} as a parameter, my guess its some form of unique user id but i'm not sure where to retrieve it from. 

So those are the options here. A good tool for working any of this stuff out would be to utilize the ability to inject javascript into galaxy.api NextStep(). This could allow you to scrap the needed information from the websites during their natural auth process,.

Or maybe mark a regex on https://socialclub.rockstargames.com/ajax/getGoogleTagManagerSetupData as enduri during auth process, then when it comes to pass_login_credentials method the whole uri will be available to you under 'credentials' parameter of the method. From that you could scrap the unique id and move forward. 

Hope any of this helps you with developing this plugin.

Cheers!

**Comment by tylerbrawl** [comment]
Thank you for all of this information. Creating a better games library implementation is my next priority, but it might take some time.

The https://www.rockstargames.com/auth/get-user.json call does indeed provide some very useful information, as it returns a list of all of the authenticated user's played games. The only major issue with this is that it does not account for the fact that the user may or may not actually have the game purchased from the Rockstar Warehouse. For example, I purchased GTA V on Steam, but it still ends up in that list. If there is another call somewhere that returns which games were purchased on other platforms and which were purchased on Rockstar's own stores, then this could be the solution.

**Comment by tylerbrawl** [comment]
After working on this for some time, I have developed a better method for getting the user's owned games. It still relies partially on reading the launcher's log file, but it should also check online to see which games the user has played. Here is a detailed description of how the new method works:

- Get the user's played games from https://www.rockstargames.com/auth/get-user.json. (This file actually does return all of the user's played games, contrary to prior belief.)
    - If the Rockstar Games Launcher is installed, then read the log file it generates to confirm which games are owned on the launcher and which ones are Steam/Retail. (Since the above call gives a list of all of the user's played games, regardless of where they bought them, non-launcher games should be filtered out if possible.)
    - If the Rockstar Games Launcher is not installed, or its log file cannot be read from, then the list obtained from https://www.rockstargames.com/auth/get-user.json is used in its entirety. Although the inclusion of non-launcher games is unfortunate, there does not seem to be a way around this. Still, this will provide a more accurate list of a user's library than the previous method of adding every game would.

This is likely the best possible solution until somebody can figure out how the Rockstar Games Launcher gets a user's entitlements correctly. The new method for obtaining a user's games will be available starting with release v0.2.

**Comment by tylerbrawl** [comment]
With the release of v0.2, I am going to close this issue. If anybody has any issues with the latest version of the plugin regarding getting the user's games library, or if anybody has an idea for getting the direct list of the user's launcher game entitlements, then I will open this issue again.
