### ISSUE TITLE
Platform ID of who depends?

### ISSUE THREAD

**Issue by Danyelalejandro** [tylerbrawl/Galaxy-Plugin-Rockstar#3]
Hello @tylerbrawl 

I have twitted GOG developers about including platform ID so launcher is usable:
![image](https://user-images.githubusercontent.com/53067616/66258634-351c2800-e76d-11e9-9cf8-13ce76636728.png)
https://twitter.com/DanielLievan/status/1180142423013560321?s=20
And they answered this:
![image](https://user-images.githubusercontent.com/53067616/66258636-3baa9f80-e76d-11e9-95ec-5d91beda8072.png)
https://twitter.com/LKukawski/status/1180148188067573765?s=20
I have reported this on the cogwheel of GLX and nothing seems to happen...
They have replied something to you?
Thanks a lot!!!

**Comment by tylerbrawl** [comment]
As far as I can tell, you will need to talk to the creator of the Twitch plugin to get their integration to launch games. As for adding the platform ID, there is nothing I can really do about that. I agree that they should add one, but I cannot do it myself. If GOG isn't to be held responsible for adding the platform ID, then who is?

Also, this plugin does work, as far as I can tell; it's just listed as Riot within Galaxy 2.0. Is there a specific issue you are having with it aside from the name being this?

**Comment by tylerbrawl** [comment]
I just checked the repository for the Galaxy Plugin API, and they have made a commit that adds the Rockstar Games Launcher platform ID to the client. Once the next version of the API is released, I will update this plugin's platform ID to Rockstar.

**Comment by Danyelalejandro** [comment]
Thank you dear @tylerbrawl Just let us know so we can start to use the plugin

**Comment by tylerbrawl** [comment]
You can still use the plugin while you wait. The only thing that would be wrong with it is the name. The plugin is listed as Riot right now, but it is really a plugin for the Rockstar Games Launcher; the name is wrong because the platform was not yet added to the API at the time of the release.

**Comment by tylerbrawl** [comment]
This has been fixed with the final release of v0.2. The platform ID is now correctly listed as Rockstar.
