### ISSUE TITLE
[RDR2] Stats display PS4 trophies instead of PC achievements

### ISSUE THREAD

**Issue by Ryusennin** [tylerbrawl/Galaxy-Plugin-Rockstar#33]
I have both versions of RDR2 and the plugin only displays the trophies I earned on PS4 last year, not the few PC achievements I recently unlocked.

Both versions are linked to the same Rockstar social account.

**Comment by tylerbrawl** [comment]
This is an underlying issue with Galaxy 2.0, and is nothing that I can fix. The Galaxy 2.0 client shows your achievements for a game across all platforms on the same screen. In addition, this plugin currently has no achievement support for games on the Rockstar Games Launcher (at least, not until GOG themselves add support for it - see #12).

The best thing to do would be to request to GOG from the cogwheel to allow viewing achievements on a per-platform basis.
