### ISSUE TITLE
Can no longer launch rock star games with GOG

### ISSUE THREAD

**Issue by Skyryk** [tylerbrawl/Galaxy-Plugin-Rockstar#44]
Gog will say that they are lunching a rockstar game, but the client will not open if closed, and the game will not launch if the client is already open. Only get a notification that the game is being launched, but the game is never gets launched. This is on windows.

**Comment by rblaine95** [comment]
What is your plugin version?
afaik, this was fixed in [v0.3.4](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/releases/tag/v0.3.4)

**Comment by tylerbrawl** [comment]
@rblaine95 is right. If you are using a different version, then let me know.

**Comment by Skyryk** [comment]
Sorry about that. I was using the v0.3.3 on the friends of gog fork, so i didn't even notice that there was a newer version released on this repo.

**Comment by tylerbrawl** [comment]
Don't worry about it. There appears to be a delay of a few days between releases on this repository and releases on the fork from @FriendsOfGalaxy. I will continue to upload releases on this repository for some time.
