### ISSUE TITLE
3.5 crashes: old API version

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [tylerbrawl/Galaxy-Plugin-Rockstar#56]
You probably forgot to update API version on `fog_release`, so we got now:

```
ImportError: cannot import name 'UserInfo' from 'galaxy.api.types'
```

Better user requirements.txt on master for routine testing before release. We should also test before merging PR...

**Comment by tylerbrawl** [comment]
Sorry about that. I forgot all about the ```requirements.txt``` file for dependencies. It has been updated with the latest commit.

**Comment by FriendsOfGalaxy** [comment]
Bump version to be sync for users.

**Comment by tylerbrawl** [comment]
Alright, it's done. I tested it on Windows, but you may want to test it on Mac yourself.
