### ISSUE TITLE
Reading log file can crash on unicode characters

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [tylerbrawl/Galaxy-Plugin-Rockstar#6]
Hey,

when reading the rockstar log file in order to parse owned games the method can crash if it encounters characters which it can't decode.

> 2019-10-09 12:43:57,703 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID gtasa is owned!
> 2019-10-09 12:43:57,705 - root - ERROR - Task exception was never retrieved
> future: <Task finished coro=<RockstarPlugin.check_for_new_games() done, defined at C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar\plugin.py:266> exception=UnicodeDecodeError('utf-8', b'Warto\x9c\xe6 skr\xf3tu : b9e3ce80180', 5, 6, 'invalid start byte')>
> Traceback (most recent call last):
>   File "C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar\plugin.py", line 269, in check_for_new_games
>     await self.get_owned_games()
>   File "C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar\plugin.py", line 197, in get_owned_games
>     for line in frb:
>   File "C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar\file_read_backwards\file_read_backwards.py", line 112, in next
>     return r.decode(self.encoding)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 5: invalid start byte
> 2019-10-09 12:44:01,495 - root - DEBUG - Received 55 bytes of data

I would propose to ignore the error at that line and move forward if the info you seek is sure to not have any special characters (not really familiar with the module you are using for file reading so i can't help more here)

**Comment by tylerbrawl** [comment]
I have made the commit https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/commit/76ab5fef05fed9ca2ee8b09cc790d81f3c20250d to attempt to fix this issue. The method now reads the log file and checks for a UnicodeDecodeError; if one is found, then the method moves to the next line.
