### ISSUE TITLE
Error while launching GTA V

### ISSUE THREAD

**Issue by DarkNeooo** [tylerbrawl/Galaxy-Plugin-Rockstar#64]
Hey, it's me again. Now I have problem with launching GTA V. When I try to turn the game on, I get a prompt from GTA process:
![GTA5_2019-12-14_14-40-40](https://user-images.githubusercontent.com/3858674/70849522-c7ccf780-1e7f-11ea-8cad-73a94f9481e0.png)
and there is no indication from Rockstar Launcher that it's trying to launch the game. I don't think there is in log but I attached it anyway (request to launch at: 2019-12-14 14:40:08,036).
[plugin-rockstar.log](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/3963883/plugin-rockstar.log)

When I changed 
`"launchEXE": "GTA5.exe"` to
`"launchEXE": "PlayGTAV.exe"`
in _game_cache.py_ then the game started but I think your plugin didn't track the playtime.

**Comment by tylerbrawl** [comment]
Thank you for pointing that out. I do not own GTA V on the Rockstar Games Launcher, so I have been unable to verify that. I will go ahead and make this fix for the latest version.

**Comment by DarkNeooo** [comment]
Unfortunately setting _PlayGTAV.exe_ as _launchEXE_ stops the plugin from tracking gametime as I said before.

**Comment by tylerbrawl** [comment]
Sorry about that. Would you be able to quickly test this attached version? I incorporated a feature that might fix it.

[**plugin.zip**](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/3986457/plugin.zip)

**Comment by tokrol** [comment]
The fix works fine. Thank you.

**Comment by tylerbrawl** [comment]
No problem. Thanks for letting me know.
