### ISSUE TITLE
Sensitive logs leftovers

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [tylerbrawl/Galaxy-Plugin-Rockstar#66]
Hey,

there is a place in code which will log sensitive info regardless of the LOG_SENSITIVE_DATA variable. 

>  async def pass_login_credentials(self, step, credentials, cookies):
>         log.debug("ROCKSTAR_COOKIE_LIST: " + str(cookies))
>         for cookie in cookies:
>         ........

**Comment by tylerbrawl** [comment]
Good catch. I made sure to implement that for this version and push it to ```fog_release```.
