### ISSUE TITLE
Proper state of running games

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [tylerbrawl/Galaxy-Plugin-Rockstar#7]
Hey, 

i've noticed that when launching game you send its status as LocalGameState.Running, this isn't properly handled by Galaxy. In order for the play button in Galaxy to be grayed out and the game be recognized as running its state needs to be sent as LocalGameState.Installed | LocalGameState.Running.

from the documentation 

> Possible states that a local game can be in. For example a game which is both installed
> and currently running should have its state set as a “bitwise or” of Running and Installed flags:
> local_game_state=<LocalGameState.Running|Installed: 3>

so this
```
async def launch_game(self, game_id):
        title_id = get_game_title_id_from_ros_title_id(game_id)
        self.running_games_pids[title_id] = [await self._local_client.launch_game_from_title_id(title_id), True]
        log.debug("ROCKSTAR_PIDS: " + str(self.running_games_pids))
        if self.running_games_pids[title_id][0] != '-1':
            self.update_local_game_status(LocalGame(game_id, LocalGameState.Running))
```

would have to look like this

```
async def launch_game(self, game_id):
        title_id = get_game_title_id_from_ros_title_id(game_id)
        self.running_games_pids[title_id] = [await self._local_client.launch_game_from_title_id(title_id), True]
        log.debug("ROCKSTAR_PIDS: " + str(self.running_games_pids))
        if self.running_games_pids[title_id][0] != '-1':
            self.update_local_game_status(LocalGame(game_id, LocalGameState.Installed | LocalGameState.Running))
```

hope this helps.

**Comment by tylerbrawl** [comment]
Thanks for pointing this out. I have fixed this with commit https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/commit/226a30871d94691cd2b00e952b211ff6e3b352d6.
