### ISSUE TITLE
Lost integration

### ISSUE THREAD

**Issue by hightower5** [tylerbrawl/Galaxy-Plugin-Rockstar#8]
The  connection to my account is often disconnected.

**Comment by tylerbrawl** [comment]
How often does it disconnect? Also, are you using any variant of v0.1 still? I am working with v0.2 Pre-Release 2, and it seems to disconnect far less often than v0.1 did. It also seems to be fairly stable, although there have been some random crashes. Still, clicking on "Retry" after it does crash always works.

In case you were wondering, the entire method for authenticating the user was overhauled to provide more internal flexibility starting with v0.2. In the current version of this update, the user *should* remain authenticated for 10 hours after logging out, with the timer resetting if they log in again.

**Comment by tylerbrawl** [comment]
I apologize for this taking so long to fix; it was a rather complicated undertaking. The final release of v0.2 now keeps the user authenticated for 20 years, with that time period resetting if the user logs in again.
