### ISSUE TITLE
Using a portable install of Rockstar Games Launcer.  WINDOWS_UNINSTALL_KEY has no reference to "Rockstar Games Launcher"

### ISSUE THREAD

**Issue by cooperate** [tylerbrawl/Galaxy-Plugin-Rockstar#86]
Rockstar Launcher is not installed in the default location.  When I launch a game, it opens my browser directing me to install the client.  I see it uses the registry to infer the install path, but my portable install does not add this information to the registry.  Perhaps offer an override option in the config for portable installs which will supersede the registry path.

```
    def get_local_launcher_path(self):
        try:
            # The uninstall key for the launcher is called Rockstar Games Launcher.
            key = OpenKey(self.root_reg, WINDOWS_UNINSTALL_KEY + "Rockstar Games Launcher")
            dir, type = QueryValueEx(key, "InstallLocation")
            self.installer_location = dir[:-1] + "\\Launcher.exe\""
            if LOG_SENSITIVE_DATA:
                log.debug("ROCKSTAR_INSTALLER_PATH: " + self.installer_location)
            else:
                log.debug("ROCKSTAR_INSTALLER_PATH: ***")
        except WindowsError:
            self.installer_location = None
        return self.installer_location
```

**Comment by tylerbrawl** [comment]
Thank you for pointing that out. I have just pushed commit c3a2ff0 to the ``fog_release`` branch, which adds the ability to override the path to the Rockstar Games Launcher. This also required modifying the ``galaxyutils`` module for true ``str`` support, so if you wish to try this fix early, then you will need to update that also. Lastly, be sure to delete your previous ``config.cfg`` file.
